Autofill Version with SVN Revision if 0 and Release with BuildNr if 0

diff --git a/svn2rpm b/svn2rpm
--- a/svn2rpm
+++ b/svn2rpm
@@ -132,12 +132,27 @@ if test "${#SPECFILE[@]}" -ne 1 ; then
 	die "There is not exactly 1 spec file (${SPECFILE[@]})"
 fi
 
-# patch rev into spec file
-sed -i -e "s/^\(Release:[\t ]\+[^%]\+\)/\1.$REV$BUILDNR/" "$SPECFILE" || die "Could not patch REV into '$SPECFILE'"
-
 # get package name and version from spec file
 PACKAGE_NAME="$( sed -ne '/Name:/{s/.*:[\t ]\+\(.*\)/\1/;P}' "$SPECFILE" )"
 PACKAGE_VERSION="$( sed -ne '/Version:/{s/.*:[\t ]\+\(.*\)/\1/;P}' "$SPECFILE" )"
+PACKAGE_RELEASE="$( sed -ne '/Release:/{s/.*:[\t ]\+\(.*\)/\1/;P}' "$SPECFILE" )"
+
+if ((PACKAGE_VERSION == 0)) ; then
+    # version 0 means put SVN Revision as version
+    PACKAGE_VERSION=$REV
+    sed -i -e "s/^\(Version:[\t ]\+[^%]\+\)/Version: $REV/" "$SPECFILE" || die "Could not patch REV as Package Version into '$SPECFILE'"
+fi
+
+if (( PACKAGE_RELEASE == 0 )) ; then
+    # release 0 means put extra build info as release or leave at 0
+    if [[ "$BUILDNR" ]] ; then
+        sed -i -e "s/^\(Release:[\t ]\+[^%]\+\)/Release: $BUILDNR/" "$SPECFILE" || die "Could not patch BUILDNR as Package Release into '$SPECFILE'"
+    fi
+else
+    # patch rev into spec file
+    sed -i -e "s/^\(Release:[\t ]\+[^%]\+\)/\1.$REV$BUILDNR/" "$SPECFILE" || die "Could not append REV and BUILDNR to Package Release into '$SPECFILE'"
+fi
+
 PACKAGE="$PACKAGE_NAME-$PACKAGE_VERSION"
 test "$PACKAGE" = "-" && die "Could not determine correct package name and version from SPEC file (got $PACKAGE)"
 
@@ -190,3 +205,5 @@ if test "$RESULT_FILES" ; then
 else
 	die "No RPMs were created"
 fi
+
+# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
